remove references to yum

diff --git a/home/bin/getupdates b/home/bin/getupdates
--- a/home/bin/getupdates
+++ b/home/bin/getupdates
@@ -1,5 +1,5 @@
 #!/bin/bash
-# updates packages; tries yum first, then apt-get
+# updates packages; tries dnf first, then apt-get
 
 function command_exists {
 	# http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
@@ -13,17 +13,11 @@ then
 fi
 
 
-if command_exists yum ;
-then
-	sudo yum update -y --changelog
-	exit $?
-fi
-
 if command_exists apt-get ;
 then
 	sudo apt-get update && sudo apt-get dist-upgrade -y
 	exit $?
 fi
 
-echo "Couldn't find yum or apt-get, exiting." 1>&2;
+echo "Couldn't find dnf or apt-get, exiting." 1>&2;
 exit 1
